- docker-compose-dev.yml
- pwa/src/apiService/resources/components.ts
- pwa/src/hooks/components.ts
- pwa/src/templates/componentDetail/ComponentsDetailTemplate.tsx
- pwa/src/templates/componentResult/ComponentResultsTemplate.tsx
- pwa/src/templates/components/ComponentsTemplate.tsx
This pull request re-implements the retrieval of components from the gateway _and_ adds the `getOne` methods. 
Note: the data doesn't come with `layer` and therefore the `layer` filter broke. I think we should just merge it since we'll be ahead of the backend for a while probably.
Also updates the yaml.
> Feature/oc 13/gateway data

- docker-compose-dev.yml
Updated docker compose file to deprettify the file and fix an error
> Updated Docker Compose File

- pwa/src/context/filters.ts
- pwa/src/data/filters/applicatiefuncties.ts
- pwa/src/data/filters/bedrijfsfuncties.ts
- pwa/src/data/filters/bedrijfsservices.ts
- pwa/src/data/filters/index.ts
- pwa/src/data/filters/referentieComponenten.ts
- pwa/src/templates/templateParts/filters/verticalFilters/VerticalFiltersTemplate.tsx
This pull request adds all GEMMA filtering.
**Note:** the select field population data is temporarily added to the codebase and will be removed once the gateway supports it.
> Feature/oc 39/gemma filters

- pwa/package-lock.json
- pwa/package.json
- pwa/src/apiService/apiService.ts
- pwa/src/layout/Head.tsx
- pwa/src/layout/Layout.tsx
- pwa/static/env.js
> ADD react-helmet and sessionStorage env implementation

- README.md
This in order to be a draft for the content of the installation page (although that will have to be translated to Dutch)
> Rewrite the quick start readme, and add some information about Helm

- pwa/gatsby-config.js
- pwa/src/templates/componentDetail/ComponentsDetailTemplate.module.css
- pwa/src/translations/en.ts
- pwa/src/translations/nl.ts
Intentionally hiding the image on mobile due to lack of space.
> REFACTOR component detail page heading

- pwa/src/apiService/apiService.ts
Removes all (now redundant) ts-ignore checks.
> REMOVE all ts-ignore statements

- pwa/package-lock.json
- pwa/package.json
`conduction/components` has been updated 👍🏼
> UP conduction/components with updated PrimaryTopNav

- pwa/src/components/tableWrapper/TableWrapper.tsx
I've created an issue (OC-524) to refactor this component (I think we can make it much less complex). Error has been fixed in this pull request though.
> REFACTOR TableWrapper to ensure .current exists

- pwa/src/styling/design-tokens/component-overrides.css
- pwa/static/themes/rotterdam.css
focus ring toegevoegd voor header
> Feature/oc 652/focusring

- pwa/src/styling/design-tokens/component-overrides.css
- pwa/src/templates/components/ComponentsTemplate.module.css
- pwa/src/templates/components/ComponentsTemplate.tsx
- pwa/static/themes/rotterdam.css
alert bij component naar Utrecht component fixen
> Feature/oc 672/alert component

- pwa/src/components/tableWrapper/TableWrapper.tsx
- pwa/src/templates/templateParts/filters/verticalFilters/VerticalFiltersTemplate.tsx
- pwa/src/templates/templateParts/resultsTemplates/table/TableResultTemplate.tsx
- pwa/static/themes/rotterdam.css
status badge verandert naar die van Utrecht en gestyled naar het firma
> Styling/oc 678/status badge

- pwa/package-lock.json
- pwa/package.json
- pwa/src/templates/templateParts/componentCardsAccordion/ComponentCardsAccordionTemplate.module.css
- pwa/src/templates/templateParts/componentCardsAccordion/ComponentCardsAccordionTemplate.tsx
- pwa/static/env.js
- pwa/static/themes/rotterdam.css
> Refactor/button group/application discription

- pwa/src/pages/documentation/contact.tsx
- pwa/src/templates/documentation/contactDocumentation/ContactDocumentationTemplate.module.css
- pwa/src/templates/documentation/contactDocumentation/ContactDocumentationTemplate.tsx
- pwa/src/templates/templateParts/footer/FooterTemplate.tsx
- pwa/src/templates/templateParts/header/HeaderTemplate.tsx
- pwa/src/translations/en.ts
- pwa/src/translations/nl.ts
Reverts OpenCatalogi/web-app#269
> Revert "Feature/oc 690/contact and nav"

- .github/workflows/dockerimage.yml
Reverts OpenCatalogi/web-app#285
> Revert "Activate actions on refinement-demo"

- pwa/src/components/resultsDisplaySwitch/ResultsDisplaySwitch.tsx
- pwa/src/templates/categoryDetailTemplate/CategoryDetailTemplate.tsx
- pwa/src/templates/componentDetail/ComponentsDetailTemplate.tsx
- pwa/src/templates/templateParts/filters/verticalFilters/VerticalFiltersTemplate.tsx
- pwa/src/templates/templateParts/resultsTemplates/table/TableResultTemplate.tsx
- pwa/src/templates/templateParts/submitUrl/SubmitUrlTemplate.tsx
- pwa/src/translations/en.ts
- pwa/src/translations/nl.ts
- Removes all unused classNames;
- Moves (clickable) repository tag to a button, for UX;
- Adds the tags as described in the issue.
> Feature/oc 752/tags

- pwa/src/templates/applicationsDetailTemplate/ApplicationsDetailTemplate.module.css
- pwa/src/templates/applicationsDetailTemplate/ApplicationsDetailTemplate.tsx
- pwa/src/templates/applicationsTemplate/ApplicationsTemplate.tsx
- pwa/src/templates/categoryDetailTemplate/CategoryDetailTemplate.module.css
- pwa/src/templates/categoryDetailTemplate/CategoryDetailTemplate.tsx
- pwa/src/templates/componentDetail/ComponentsDetailTemplate.tsx
- pwa/src/templates/templateParts/componentCardsAccordion/ComponentCardsAccordionTemplate.tsx
- pwa/src/templates/templateParts/componentCardsAccordion/header/ComponentCardsAccordionHeaderTemplate.module.css
- pwa/src/templates/templateParts/dependenciesTemplates/relationsDependenciesTemplate/RelationsDependenciesTemplate.tsx
- pwa/src/templates/templateParts/resultsTemplates/cards/CardsResultTemplate.tsx
A set of small fixes throughout the application. Mostly regarding handling showing no content.
> REFACTOR small fixes

- pwa/src/templates/documentation/usageDocumentation/UsageDocumentationTemplate.tsx
- pwa/src/templates/templateParts/submitUrl/SubmitUrlTemplate.module.css
- pwa/src/templates/templateParts/submitUrl/SubmitUrlTemplate.tsx
- pwa/src/translations/en.ts
- pwa/src/translations/nl.ts
- Adds the SubmitUrlTemplate component to the other documentation page;
- Some minor design changes to the component.
> Feature/oc 741/component toevoegen

- pwa/package-lock.json
- pwa/package.json
Worked out-of-the-box 🚀 
Thought we might as well merge it, so that the package is up-to-date again.
> UP conduction/components

- pwa/src/components/categoryCard/CategoryCard.tsx
- pwa/src/templates/applicationsDetailTemplate/ApplicationsDetailTemplate.tsx
- pwa/src/templates/landing/LandingTemplate.tsx
- pwa/src/templates/organizationDetail/OrganizationDetailTemplate.tsx
- pwa/src/templates/templateParts/categoriesCardsAccordion/header/CategoriesCardsAccordionHeaderTemplate.tsx
- pwa/src/templates/templateParts/componentCardsAccordion/header/ComponentCardsAccordionHeaderTemplate.tsx
- pwa/src/templates/templateParts/componentCategoryAccordion/header/ComponentCategoryAccordionHeaderTemplate.tsx
- pwa/src/templates/templateParts/filters/verticalFilters/VerticalFiltersTemplate.module.css
- pwa/src/templates/templateParts/filters/verticalFilters/VerticalFiltersTemplate.tsx
- pwa/static/themes/rotterdam.css
- pwa/static/themes/theme.css.example
- pwa/static/themes/utrecht.css
This pull request removes all Den Haag Divider implementations, and replaces it with the Utrecht Separator. Tokens have been added to the themes.
> REFACTOR Den Haag divider to Utrecht separator and add tokens to themes

- pwa/package-lock.json
- pwa/package.json
- pwa/src/styling/themeProvider/ThemeProvider.tsx
- pwa/src/templates/templateParts/filters/horizontalFilters/HorizontalFiltersTemplate.tsx
- pwa/src/templates/templateParts/filters/organizationSearchFilterTemplate/OrganizationSearchFilterTemplate.tsx
- pwa/src/templates/templateParts/filters/verticalFilters/VerticalFiltersTemplate.tsx
- pwa/src/templates/templateParts/loginForm/LoginFormTemplate.tsx
- pwa/src/templates/templateParts/searchComponent/SearchComponentTemplate.tsx
- pwa/src/templates/templateParts/submitUrl/SubmitUrlTemplate.tsx
This pull request removes all FormFieldInputs from Den Haag (and its dependencies). The form elements were already wrapped in _another_ wrapper by Utrecht, making the FormFieldInputs redundant.
> REMOVE all Den Haag FormFieldInput wrappers

- pwa/src/styling/global.css
- pwa/src/styling/index.css
- pwa/src/templates/templateParts/categoriesAccordion/CategoriesAccordionTemplate.module.css
- pwa/src/templates/templateParts/categoriesAccordion/CategoriesAccordionTemplate.tsx
- pwa/src/templates/templateParts/categoriesAccordion/filters/CategoriesAccordionFiltersTemplate.module.css
- pwa/src/templates/templateParts/categoriesAccordion/filters/CategoriesAccordionFiltersTemplate.tsx
- pwa/src/templates/templateParts/categoriesCardsAccordion/header/CategoriesCardsAccordionHeaderTemplate.module.css
- pwa/src/templates/templateParts/componentCardsAccordion/ComponentCardsAccordionTemplate.module.css
- pwa/src/templates/templateParts/componentCardsAccordion/ComponentCardsAccordionTemplate.tsx
- pwa/src/templates/templateParts/componentCardsAccordion/header/ComponentCardsAccordionHeaderTemplate.module.css
- pwa/src/templates/templateParts/componentCategoryAccordion/ComponentCategoryAccordionTemplate.tsx
- pwa/src/templates/templateParts/componentCategoryAccordion/header/ComponentCategoryAccordionHeaderTemplate.module.css
- pwa/src/templates/templateParts/dependenciesTemplates/layerDependenciesTemplate/LayerDependenciesTemplate.tsx
- pwa/src/templates/templateParts/layerAccordion/LayerAccordionTemplate.module.css
- pwa/src/templates/templateParts/layerAccordion/LayerAccordionTemplate.tsx
- pwa/src/templates/templateParts/layerAccordion/filters/LayerAccordionFiltersTemplate.module.css
- pwa/src/templates/templateParts/layerAccordion/filters/LayerAccordionFiltersTemplate.tsx
- pwa/src/templates/templateParts/resultsTemplates/layers/LayersResultTemplate.tsx
- pwa/static/themes/rotterdam.css
- pwa/static/themes/theme.css.example
- pwa/static/themes/utrecht.css
This pull request makes the accordions NLDS-ready. 
JIRA issues: OP-69, OP-72, OP-53.
> Feature/op 52/categories accordion

- pwa/src/templates/componentDetail/ComponentsDetailTemplate.tsx
- pwa/src/templates/components/ComponentsTemplate.tsx
> Feature/op 107/total results

- pwa/src/layout/Layout.tsx
- pwa/src/services/getConfig.ts
- pwa/static/.env.development
This pr will contain dummy code to test workings of getConfig on acc
> ConfigTest

- pwa/src/layout/Layout.tsx
- pwa/src/services/getConfig.ts
- pwa/static/.env.development
Reverts OpenCatalogi/web-app#415
> Revert "ConfigTest"
